config/routes.rb
PersonalWebsite::Application.routes.draw do
  root 'projects#home'
  match '/project', to: 'projects#project', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/resume', to: 'static_pages#resume', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def home
  end

  def project
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

  def resume
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Eric Chew"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer fix-bottom pull-left pull-right">
  <div>
    <small>&copy; Eric Chew 2014</small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar fix-top pull-right pull-left">
  <div class="wrapper">
    <div class="logo-wrapper">
      <div id="logo">
        <div class="logo-picture"></div>
      </div>
    </div>
    <div class="border"></div>
    <nav> 
      <ul class="left-list"> 
        <li><%= link_to "Work", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      <div class="separator"></div>
      <ul class="right-list"> 
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Resume", resume_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render "/layouts/shim" %>
</head>
<body>
  <div id="wrapper">
  <%= render "/layouts/header" %>
  <%= yield %>
  <%= render "/layouts/footer" %>
  <div>
</body>
</html>

app/views/projects/home.html.erb
<div id="projects"></div>

app/views/projects/project.html.erb
<h1>Projects#project</h1>
<p>Find me in app/views/projects/project.html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Me</h1>
<p>
  MEEEEEP
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  CALL MEHHH
</p>

app/views/static_pages/resume.html.erb
<% provide(:title, "Resume") %>
<h1>Resume</h1>
<p>
  Derp
</p>